'use client';
import React from 'react';
import UserProvider from '../providers/UserProvider';
import '../styles/App.css';
import { GlobalLayout } from '../app/GlobalLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactElement | React.ReactElement[];
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <GlobalLayout>
            {children}
          </GlobalLayout>
        </UserProvider>
      </body>
    </html>
  );
}
